name: Wconcept Best Daily Export

on:
  schedule:
    # 08:00 KST == 23:00 UTC (previous day)
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run exporter
        env:
          TZ: Asia/Seoul
        run: |
          python scripts/wconcept_best_export.py --output-dir output

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: wconcept-best-${{ github.run_id }}-${{ github.run_attempt }}
          path: output/*.csv
          if-no-files-found: error
          retention-days: 30
